const AGENTS_HIERARCHY = {
  orchestrator: {
    id: 'agents-orchestrator',
    name: 'Agents Orchestrator',
    role: 'Gerente General',
    level: 1,
    description: 'Recibe tu pedido, lo desglosa, activa los departamentos, coordina el flujo y consolida el resultado.',
    icon: 'Brain',
  },
  departments: [
    {
      id: 'estrategia',
      name: 'Estrategia & Research',
      level: 2,
      agents: [
        { id: 'trend-researcher', name: 'Trend Researcher', role: 'Investigador de mercado' },
        { id: 'product-manager', name: 'Product Manager', role: 'Define features y roadmap' },
        { id: 'strategy', name: 'Strategy', role: 'Posicionamiento y plan' },
        { id: 'cultural-intelligence', name: 'Cultural Intelligence', role: 'Evaluación cultural' },
        { id: 'offer-lead-gen-strategist', name: 'Offer & Lead Gen Strategist', role: 'Diseño de ofertas' },
        { id: 'book-co-author', name: 'Book Co-Author', role: 'Contenido largo' },
        { id: 'private-domain-operator', name: 'Private Domain Operator', role: 'Mensajería directa' },
        { id: 'sprint-prioritizer', name: 'Sprint Prioritizer', role: 'Priorización' },
      ],
    },
    {
      id: 'diseno',
      name: 'Producto & Diseño',
      level: 3,
      agents: [
        { id: 'ui-designer', name: 'UI Designer', role: 'Diseño visual' },
        { id: 'ux-researcher', name: 'UX Researcher', role: 'Pruebas de usuario' },
        { id: 'brand-guardian', name: 'Brand Guardian', role: 'Identidad de marca' },
        { id: 'visual-storyteller', name: 'Visual Storyteller', role: 'Narrativa visual' },
        { id: 'image-prompt-engineer', name: 'Image Prompt Engineer', role: 'Generación de imágenes' },
        { id: 'behavioral-nudge-engine', name: 'Behavioral Nudge Engine', role: 'Psicología conductual' },
        { id: 'feedback-synthesizer', name: 'Feedback Synthesizer', role: 'Análisis de feedback' },
        { id: 'inclusive-visuals-specialist', name: 'Inclusive Visuals Specialist', role: 'Representación diversa' },
        { id: 'persona-walkthrough-specialist', name: 'Persona Walkthrough Specialist', role: 'Simulación de UX' },
        { id: 'ux-architect', name: 'UX Architect', role: 'Arquitectura de UX' },
        { id: 'whimsy-injector', name: 'Whimsy Injector', role: 'Micro-interacciones' },
      ],
    },
    {
      id: 'marketing',
      name: 'Marketing & Contenido',
      level: 4,
      agents: [
        { id: 'content-creator', name: 'Content Creator', role: 'Redacción de contenidos' },
        { id: 'social-media-strategist', name: 'Social Media Strategist', role: 'Estrategia social' },
        { id: 'seo-specialist', name: 'SEO Specialist', role: 'Optimización SEO' },
        { id: 'email-marketing-strategist', name: 'Email Marketing Strategist', role: 'Email campaigns' },
        { id: 'growth-hacker', name: 'Growth Hacker', role: 'Crecimiento viral' },
        { id: 'instagram-curator', name: 'Instagram Curator', role: 'Estrategia visual IG' },
        { id: 'tiktok-strategist', name: 'TikTok Strategist', role: 'Contenido TikTok' },
        { id: 'linkedin-content-creator', name: 'LinkedIn Content Creator', role: 'Contenido B2B' },
        { id: 'aeo-foundations-architect', name: 'AEO Foundations Architect', role: 'Optimización AI' },
        { id: 'agentic-search-optimizer', name: 'Agentic Search Optimizer', role: 'Búsqueda agentic' },
        { id: 'ai-citation-strategist', name: 'AI Citation Strategist', role: 'Visibilidad en LLMs' },
        { id: 'app-store-optimizer', name: 'App Store Optimizer', role: 'ASO' },
        { id: 'baidu-seo-specialist', name: 'Baidu SEO Specialist', role: 'SEO China' },
        { id: 'bilibili-content-strategist', name: 'Bilibili Content Strategist', role: 'Bilibili' },
        { id: 'carousel-growth-engine', name: 'Carousel Growth Engine', role: 'Carruseles virales' },
        { id: 'china-market-specialist', name: 'China Market Specialist', role: 'Mercado chino' },
        { id: 'cross-border-ecommerce', name: 'Cross-Border E-Commerce', role: 'E-commerce global' },
        { id: 'douyin-strategist', name: 'Douyin Strategist', role: 'Douyin' },
        { id: 'multi-platform-publisher', name: 'Multi-Platform Publisher', role: 'Publicación multi-plataforma' },
        { id: 'podcast-strategist', name: 'Podcast Strategist', role: 'Podcasting' },
        { id: 'reddit-community-builder', name: 'Reddit Community Builder', role: 'Comunidad Reddit' },
        { id: 'twitter-engager', name: 'Twitter Engager', role: 'Twitter/X' },
        { id: 'video-optimization-specialist', name: 'Video Optimization Specialist', role: 'Video SEO' },
        { id: 'wechat-official-account-manager', name: 'WeChat Official Account Manager', role: 'WeChat' },
        { id: 'xiaohongshu-specialist', name: 'Xiaohongshu Specialist', role: 'Xiaohongshu' },
      ],
    },
    {
      id: 'paid-media',
      name: 'Paid Media',
      level: 5,
      agents: [
        { id: 'ppc-campaign-strategist', name: 'PPC Campaign Strategist', role: 'Arquitectura de ads' },
        { id: 'search-query-analyst', name: 'Search Query Analyst', role: 'Análisis de keywords' },
        { id: 'ad-creative-strategist', name: 'Ad Creative Strategist', role: 'Creativas publicitarias' },
        { id: 'tracking-specialist', name: 'Tracking Specialist', role: 'GTM, GA4, CAPI' },
        { id: 'paid-media-auditor', name: 'Paid Media Auditor', role: 'Auditoría de ads' },
        { id: 'paid-social-strategist', name: 'Paid Social Strategist', role: 'Social Ads' },
        { id: 'programmatic-buyer', name: 'Programmatic & Display Buyer', role: 'Compra programática' },
      ],
    },
    {
      id: 'ingenieria',
      name: 'Ingeniería',
      level: 6,
      agents: [
        { id: 'developer', name: 'Developer', role: 'Desarrollo web' },
        { id: 'backend-architect', name: 'Backend Architect', role: 'APIs, DB, escalabilidad' },
        { id: 'devops-automator', name: 'DevOps Automator', role: 'CI/CD, infraestructura' },
        { id: 'ai-engineer', name: 'AI Engineer', role: 'Modelos ML, integración AI' },
        { id: 'security-architect', name: 'Security Architect', role: 'Seguridad' },
        { id: 'appsec-engineer', name: 'Application Security Engineer', role: 'Seguridad apps' },
        { id: 'code-reviewer', name: 'Code Reviewer', role: 'Revisión de código' },
        { id: 'compliance-auditor', name: 'Compliance Auditor', role: 'Cumplimiento' },
        { id: 'data-engineer', name: 'Data Engineer', role: 'Pipelines de datos' },
        { id: 'database-optimizer', name: 'Database Optimizer', role: 'Optimización DB' },
        { id: 'email-intelligence-engineer', name: 'Email Intelligence Engineer', role: 'Procesamiento emails' },
        { id: 'git-workflow-master', name: 'Git Workflow Master', role: 'Flujo Git' },
        { id: 'incident-responder', name: 'Incident Responder', role: 'Respuesta incidentes' },
        { id: 'mobile-app-builder', name: 'Mobile App Builder', role: 'Apps móviles' },
        { id: 'penetration-tester', name: 'Penetration Tester', role: 'Pentesting' },
        { id: 'prompt-engineer', name: 'Prompt Engineer', role: 'Ingeniería de prompts' },
        { id: 'rapid-prototyper', name: 'Rapid Prototyper', role: 'Prototipado rápido' },
        { id: 'senior-developer', name: 'Senior Developer', role: 'Desarrollo senior' },
        { id: 'software-architect', name: 'Software Architect', role: 'Arquitectura software' },
        { id: 'sre', name: 'SRE', role: 'Site Reliability' },
        { id: 'technical-writer', name: 'Technical Writer', role: 'Documentación técnica' },
      ],
    },
    {
      id: 'testing',
      name: 'Testing & QA',
      level: 7,
      agents: [
        { id: 'reality-checker', name: 'Reality Checker', role: 'Certificación de calidad' },
        { id: 'api-tester', name: 'API Tester', role: 'Validación de APIs' },
        { id: 'accessibility-auditor', name: 'Accessibility Auditor', role: 'WCAG' },
        { id: 'evidence-collector', name: 'Evidence Collector', role: 'Evidencia visual' },
        { id: 'performance-benchmarker', name: 'Performance Benchmarker', role: 'Benchmarking' },
        { id: 'test-results-analyzer', name: 'Test Results Analyzer', role: 'Análisis de tests' },
        { id: 'tool-evaluator', name: 'Tool Evaluator', role: 'Evaluación herramientas' },
        { id: 'workflow-optimizer', name: 'Workflow Optimizer', role: 'Optimización flujos' },
      ],
    },
    {
      id: 'ventas',
      name: 'Ventas & CRM',
      level: 8,
      agents: [
        { id: 'outbound-strategist', name: 'Outbound Strategist', role: 'Prospección' },
        { id: 'deal-strategist', name: 'Deal Strategist', role: 'Estrategia de deals' },
        { id: 'pipeline-analyst', name: 'Pipeline Analyst', role: 'Forecasting' },
        { id: 'account-strategist', name: 'Account Strategist', role: 'Crecimiento cuentas' },
        { id: 'discovery-coach', name: 'Discovery Coach', role: 'Descubrimiento' },
        { id: 'proposal-strategist', name: 'Proposal Strategist', role: 'Propuestas' },
        { id: 'sales-coach', name: 'Sales Coach', role: 'Coaching ventas' },
        { id: 'sales-engineer', name: 'Sales Engineer', role: 'Soporte técnico ventas' },
      ],
    },
    {
      id: 'finanzas',
      name: 'Finanzas & Legal',
      level: 9,
      agents: [
        { id: 'finance-tracker', name: 'Finance Tracker', role: 'Cash flow' },
        { id: 'legal-compliance', name: 'Legal Compliance Checker', role: 'Regulaciones' },
        { id: 'analytics-reporter', name: 'Analytics Reporter', role: 'Dashboards y KPIs' },
        { id: 'accounts-payable', name: 'Accounts Payable Agent', role: 'Cuentas por pagar' },
        { id: 'executive-summary-generator', name: 'Executive Summary Generator', role: 'Reportes ejecutivos' },
      ],
    },
    {
      id: 'operaciones',
      name: 'Soporte & Operaciones',
      level: 10,
      agents: [
        { id: 'support-responder', name: 'Support Responder', role: 'Atención al cliente' },
        { id: 'project-shepherd', name: 'Project Shepherd', role: 'Coordinación' },
        { id: 'studio-producer', name: 'Studio Producer', role: 'Orquestación multi-proyecto' },
        { id: 'infrastructure-maintainer', name: 'Infrastructure Maintainer', role: 'Mantenimiento infra' },
        { id: 'meeting-notes-specialist', name: 'Meeting Notes Specialist', role: 'Notas reuniones' },
        { id: 'studio-operations', name: 'Studio Operations', role: 'Operaciones estudio' },
      ],
    },
  ],
}

export default AGENTS_HIERARCHY
